// astro.config.mjs
import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap"; // 必须是默认导入
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";

/**
 * @brief 判断 URL 是否可放入 sitemap (sitemap eligibility) / Decide whether a URL belongs in the sitemap.
 * @param page 插件生成的绝对页面 URL (absolute page URL) / Absolute page URL generated by the plugin.
 * @return 仅当页面可索引时返回 true / True only for indexable pages.
 * @note 根路径只做客户端语言跳转并带有 noindex，不能与 /zh/、/en/ 竞争。
 */
const isIndexableSitemapPage = (page) => new URL(page).pathname !== "/";

export default defineConfig({
  site: "https://blog.moesegfault.dev",
  // 开发环境接受带或不带末尾斜杠的 URL；静态产物仍以目录形式输出，保留既有的 /path/ 链接语义。
  trailingSlash: "ignore",
  build: {
    format: "directory",
  },
  i18n: {
    locales: ["zh", "en"],
    defaultLocale: "zh",
    routing: {
      prefixDefaultLocale: true,
      redirectToDefaultLocale: false,
    },
  },
  integrations: [
    sitemap({
      filter: isIndexableSitemapPage,
      i18n: {
        defaultLocale: "zh",
        locales: { zh: "zh", en: "en" },
      },
    }),
  ],
  markdown: {
    shikiConfig: {
      themes: { light: "github-light", dark: "github-dark" },
      langAlias: { prompt: "markdown" },
    },
    remarkPlugins: [remarkMath],
    rehypePlugins: [rehypeKatex],
  },
  alias: {
    "@styles": "./src/styles",
    "@components": "./src/components",
    "@layouts": "./src/layouts",
    "@i18n": "./src/i18n",
    "@content": "./src/content",
  },
});
